[package]
name = "vdm-capability-daemon"
version = "0.1.0"
authors = ["iamhyc <sudofree@163.com>"]
edition = "2018"

[lib]
name = "vdm_capability_daemon"
crate-type = ["cdylib"]

[dependencies]
shellexpand = "1.0"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]