[package]
name = "vdm-daemon"
version = "0.1.0"
authors = ["iamhyc <sudofree@163.com>"]
edition = "2018"

[dependencies]
shared_memory = "0.11.4"
libc = "0.2"
errno = "0.2"
tokio = { version = "1.5.0", features = ["full"] }
